//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMinersWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperMinersWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo128 {
            get {
                object obj = ResourceManager.GetObject("Logo128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏帮助
        ///
        ///游戏介绍
        ///	Hi，欢迎来到全新的迅灵矿场，是不是感到迷茫呢，完全不知道该怎么操作，不要着急下面跟着我一步一步的来熟悉一下矿场的操作吧。
        ///首先来看一下界面首先左上角是我们公司的logo，是不是很漂亮呢。在往下依次是贡献值、积分、灵币、金币、矿石储量、矿工、钻石、矿石、碎片、当前产量、可收取矿石量，看着是不是很迷惑啊，不要着急我现在就来一一解释给你。
        ///贡献值：每消费10积分获得一点贡献值。
        ///	积分：您在迅灵旗下线上服务任意消费1元钱便会获赠10积分（暂可自动获得赠送的业务为远程协助）；
        ///	灵币：作为矿石市场的流通货币，用于交易矿石，RMB与灵币比例为1:10；
        ///	金币：使用金币可以雇佣矿工，矿工越多挖矿的速度就越快，10灵币=1000金币；
        ///	矿石储量：您可以挖矿的总数，如果没有了就要继续勘探了；
        ///	矿工：迅灵星的土著，来帮你24小时不间断挖矿的；
        ///	钻石：用矿石兑换获得，可以用来兑换商城里的实体物品，永远保值哦；
        ///	矿石：迅灵矿场核心货币，通过挖矿、娱乐中获取；
        ///	碎片：新人福利之一，可以进行娱乐中的《疯狂猜石》游戏赢取矿石；
        ///	神灵许愿：每日可以进行三次，获得碎片方式之 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Server2GameHelper {
            get {
                return ResourceManager.GetString("Server2GameHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap 迅灵矿场 {
            get {
                object obj = ResourceManager.GetObject("迅灵矿场", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
